### ISSUE TITLE
当页面里有两个窗口时，记忆输入法功能会不停地切换

### ISSUE THREAD

**Issue by r-earth-or** [mactweak/magictoy#1]
1. What feature are you using/您在使用什么功能时遇到了问题
当页面里有两个窗口时，记忆输入法功能会不停地切换

2. App version/程序版本
1.1.1 build16

3. Environment/环境

macmini m4 macos15.1

4. Describe the bug/我遇到的问题

![image](https://github.com/user-attachments/assets/643bb175-58d1-4a8d-b2b3-ddc1dffda2c4)
下面这张截图中搜索框不停地闪烁
![image](https://github.com/user-attachments/assets/13481766-8963-477b-87c9-d6277606e878)

**Comment by travisbikkle** [comment]
抱歉，请问您能否再具体一些，您是使用 command+space 打开了聚焦搜索，然后开始闪烁，还是在pycharm和apifox之间切换的时候，聚焦搜索会不停地被打开？
1. 能否告知下，您的聚焦搜索的快捷键是什么？您可以在如下位置找到该快捷键
   <img width="657" alt="image" src="https://github.com/user-attachments/assets/ae7fa229-bc4a-4c96-a25c-f7202860d0dd">

2. 您的切换输入法的快捷键是什么？
   <img width="657" alt="image" src="https://github.com/user-attachments/assets/b952af9b-807a-4b98-8058-79e349eada50">

**Comment by r-earth-or** [comment]
晚上我看看能不能复现，录个视频给你

我的复现方法是台前调度时有两个软件在一起（它们设置了不同的默认输入法）点进去之后，就会出现频繁的聚焦搜索框闪烁
关于快捷键：我交换了command键与control键（在修饰键选项卡内）因此我的切换输入法为command+空格，聚焦搜索为control+空格

**Comment by r-earth-or** [comment]
视频如下：

https://github.com/user-attachments/assets/b08e2d1f-2c3f-4c7f-a8b5-cf2c7495bc97

其中我的浏览器与pycharm的默认输入法不同

**Comment by travisbikkle** [comment]
感谢您的反馈，经过排查，在台前调度、交换command和control键都没有导致此现象出现。

只有在更改了切换输入法的默认快捷键（⌃ 空格键）之后，才能复现该问题。

如果您的情况确实是这个原因，您可以参考 [https://mactoys.eusoftbank.com/docs/autoime](https://mactoys.eusoftbank.com/docs/autoime) 还原该设置。
如果不是，您可以继续在此issue反馈。

MagicToy的下一个版本将开放一个选择，让用户自定义选择切换输入法的快捷键。但是由于系统某些限制，可能只会在control space和command space两者之间二选一，而不是选择任意的快捷键，比如 f18 等。
