### ISSUE TITLE
希望剪贴板功能可以单击或双击后粘贴并关闭窗口

### ISSUE THREAD

**Issue by r-earth-or** [mactweak/magictoy#2]
希望剪贴板功能可以单击或双击后粘贴并关闭窗口
目前的操作逻辑有点过于难受
如果能实现类似paste的操作逻辑就更好了

**Comment by travisbikkle** [comment]
谢谢您的反馈，这个功能已经在做了，预计在下一个版本就加入进去

**Comment by travisbikkle** [comment]
您好，MagicToy 1.1.2 版本已经发布，现在支持从剪切板双击或按回车直接粘贴到其它程序，并且大幅提升了复制多个图片的性能，您可以在AppStore中直接更新。[AppStore](https://apps.apple.com/us/app/magictoy/id6737158347)

如果您的试用已经过期，您可以联系support@eusoftbank.com申请3个月的会员礼品卡。
